// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package cmd

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gcmd"

	"openetl-go/internal/logic/app"
	"openetl-go/internal/consts"
	"openetl-go/internal/service"
)

var (
	Main = gcmd.Command{
		Name:  "main",
		Usage: "main",
		Brief: "start openetl-go ETL/CDC service",
		Func: func(ctx context.Context, parser *gcmd.Parser) (err error) {
			// Structured (JSON stdout) logging before any g.Log() call (P5-16).
			app.ConfigureStructuredLogging()
			// 打印版本号
			g.Log().Infof(ctx, "OpenETL-Go Version: %s", consts.Version)

			a := service.App()

			// 配置静态文件服务（前端 UI，API 反代路由先于静态路由注册）
			a.SetupStaticFiles()

			// 启动 ETL 管道服务（role: standalone 默认 / master / worker）
			a.StartETLAsync(ctx)

			// 注册优雅关闭
			go a.WaitForShutdown()

			// 启动 HTTP 服务器
			g.Server().Run()
			return nil
		},
	}
)
