#!/usr/bin/env bash
# RA-5: real portable backups + vendor SQL dumps, generated from isolated data.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
secret_backend="${1:-all}"
if [ "$secret_backend" = all ]; then
  for backend in sqlite mysql postgres; do bash "$0" "$backend"; done
  exit
fi
case "$secret_backend" in sqlite|mysql|postgres) ;; *) echo 'backend must be sqlite, mysql or postgres' >&2; exit 2 ;; esac
command -v go >/dev/null || { echo 'Go is required for the artifact fixture' >&2; exit 2; }
command -v python3 >/dev/null || { echo 'python3 is required for scanning/dumping' >&2; exit 2; }
. "$ROOT/hack/container-cli.sh"
fixture_dir="$(mktemp -d "${TMPDIR:-/tmp}/openetl-secret-${secret_backend}.XXXXXX")"
container_id=""
cleanup() {
  if [ -n "$container_id" ]; then "$CONTAINER_CLI" rm -fv "$container_id" >/dev/null; fi
  rm -rf "$fixture_dir"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# All connection values below are test-only and generated by this invocation.
unset ETL_SPEC_ENCRYPTION_KEY ETL_SPEC_ENCRYPTION_KEY_ID ETL_SPEC_ENCRYPTION_PREVIOUS_KEYS ETL_STORAGE_DSN
export SECRET_SQLITE_PATH="$fixture_dir/metadata.db" SECRET_DSN=""
cli_backend="$secret_backend"
if [ "$secret_backend" != sqlite ]; then
  detect_container_cli
  name="openetl-secret-${secret_backend}-$(date +%s)-$$"
  if [ "$secret_backend" = mysql ]; then
    container_id="$("$CONTAINER_CLI" run -d --name "$name" -e MYSQL_ROOT_PASSWORD=secret-drill-only -e MYSQL_DATABASE=openetl_secret -p 127.0.0.1::3306 docker.io/library/mysql:8.0)"
    secret_port="$("$CONTAINER_CLI" port "$container_id" 3306 | head -n 1 | sed 's/.*://')"
    export SECRET_DSN="root:secret-drill-only@tcp(127.0.0.1:${secret_port})/openetl_secret?parseTime=true&multiStatements=true"
    ready() { "$CONTAINER_CLI" exec "$container_id" mysql --protocol=tcp -h127.0.0.1 -uroot -psecret-drill-only -e 'SELECT 1' >/dev/null 2>&1; }
  else
    cli_backend=postgresql
    container_id="$("$CONTAINER_CLI" run -d --name "$name" -e POSTGRES_PASSWORD=secret-drill-only -e POSTGRES_DB=openetl_secret -p 127.0.0.1::5432 docker.io/library/postgres:16-alpine)"
    secret_port="$("$CONTAINER_CLI" port "$container_id" 5432 | head -n 1 | sed 's/.*://')"
    export SECRET_DSN="postgres://postgres:secret-drill-only@127.0.0.1:${secret_port}/openetl_secret?sslmode=disable"
    ready() { "$CONTAINER_CLI" exec "$container_id" pg_isready -h127.0.0.1 -U postgres -d openetl_secret >/dev/null 2>&1; }
  fi
  for ((attempt=0; attempt<60; attempt++)); do if ready; then break; fi; sleep 1; done
  if ! ready; then echo "$secret_backend did not become ready" >&2; exit 1; fi
fi

printf 'etl:\n  profile: development\n' > "$fixture_dir/config.yaml"
CGO_ENABLED=0 go build -o "$fixture_dir/openetl-go" .
CGO_ENABLED=0 go build -o "$fixture_dir/fixture" ./hack/cmd/secret-artifact-fixture
fixture() { "$fixture_dir/fixture" "$1" "$secret_backend" "$fixture_dir"; }
cli() {
  ETL_STORAGE_DSN="$SECRET_DSN" "$fixture_dir/openetl-go" --config "$fixture_dir/config.yaml" \
    --storage "$cli_backend" --data-dir "$fixture_dir/data" --sqlite-path "$SECRET_SQLITE_PATH" "$@"
}
dump_sql() {
  case "$secret_backend" in
    mysql) "$CONTAINER_CLI" exec "$container_id" mysqldump -uroot -psecret-drill-only --single-transaction --no-tablespaces --set-gtid-purged=OFF openetl_secret > "$1" ;;
    postgres) "$CONTAINER_CLI" exec "$container_id" pg_dump -U postgres -d openetl_secret > "$1" ;;
    sqlite) python3 - "$SECRET_SQLITE_PATH" > "$1" <<'PY'
import sqlite3, sys
with sqlite3.connect(sys.argv[1]) as db:
    for line in db.iterdump():
        print(line)
PY
      ;;
  esac
}
scan() { bash ./hack/check-plaintext-secrets.sh "$1" --needles-file "$fixture_dir/needles.txt"; }
expect_rejection() {
  local label="$1"; shift
  local status=0
  "$@" > "$fixture_dir/rejection.log" 2>&1 || status=$?
  if [ "$status" -ne 1 ]; then
    cat "$fixture_dir/rejection.log" >&2
    echo "expected exit 1 for $label, got $status" >&2; exit 1
  fi
  echo "EXPECTED_REJECTION: $label"
}

echo "==> $secret_backend: plaintext detection and missing-key failure"
fixture seed
dump_sql "$fixture_dir/dirty.sql"
expect_rejection 'real legacy SQL dump contains plaintext' scan "$fixture_dir/dirty.sql"
expect_rejection 'readonly secret check detects legacy rows' cli --check-secrets
expect_rejection 'migration cannot succeed without a key' cli --remediate-secrets

export ETL_SPEC_ENCRYPTION_KEY_ID=new
export ETL_SPEC_ENCRYPTION_KEY="$(python3 -c 'import base64; print(base64.b64encode(bytes([34])*32).decode())')"
export ETL_SPEC_ENCRYPTION_PREVIOUS_KEYS="old=$(python3 -c 'import base64; print(base64.b64encode(bytes([17])*32).decode())')"
cli --remediate-secrets
cli --check-secrets
fixture verify
fixture remember
cli --remediate-secrets
fixture compare

echo "==> $secret_backend: actual portable backup, JSONL export and vendor SQL dump"
cli --backup-file "$fixture_dir/portable.json"
dump_sql "$fixture_dir/clean.sql"
scan "$fixture_dir/portable.json"
scan "$fixture_dir/clean.sql"
fixture diagnostic
for artifact in "$fixture_dir"/clean-jsonl/openetl-backup-*/*.jsonl; do scan "$artifact"; done

fixture inject
cli --backup-file "$fixture_dir/dirty-portable.json"
expect_rejection 'real generated portable product with an injected value leak' scan "$fixture_dir/dirty-portable.json"
cli --restore-file "$fixture_dir/portable.json"
fixture compare
fixture verify

if [ -n "${SECRET_ARTIFACT_OUTPUT:-}" ]; then
  archive_dir="$SECRET_ARTIFACT_OUTPUT/$secret_backend"
  mkdir -p "$archive_dir"
  cp "$fixture_dir/portable.json" "$archive_dir/portable.json"
  cp "$fixture_dir/clean.sql" "$archive_dir/clean.sql"
  go version > "$archive_dir/go-version.txt"
  git rev-parse HEAD > "$archive_dir/head.txt"
  python3 - "$archive_dir" <<'PY'
import hashlib, json, pathlib, sys
root = pathlib.Path(sys.argv[1])
checks = ['legacy_sql_rejected','missing_key_rejected','descriptor_dsn_encrypted','migration_idempotent','old_key_readable','portable_and_sql_clean','dirty_portable_rejected','ciphertext_restore_identical']
record = {'backend':root.name, 'checks':dict.fromkeys(checks,'passed'), 'sha256':{name:hashlib.sha256((root/name).read_bytes()).hexdigest() for name in ('portable.json','clean.sql')}}
(root/'result.json').write_text(json.dumps(record,indent=2)+'\n')
PY
fi
echo "RA-5 $secret_backend real secret-artifact e2e PASS"
