// =================================================================================
// This is auto-generated by GoFrame CLI tool once. Fill this file as you wish.
// =================================================================================

package sync

import (
	"context"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/ClickHouse/clickhouse-go/v2"
	"github.com/ClickHouse/clickhouse-go/v2/lib/driver"
	"github.com/go-mysql-org/go-mysql/canal"
	"github.com/go-mysql-org/go-mysql/mysql"
	"github.com/go-mysql-org/go-mysql/replication"
	"github.com/go-mysql-org/go-mysql/schema"
	"github.com/gogf/gf/v2/frame/g"

	"openetl-go/internal/model/entity"
	"openetl-go/internal/service"
)

func init() {

}

// sClickHouseTarget ClickHouse 同步目标
type sClickHouseTarget struct {
	chConn driver.Conn
	config *entity.TargetConfig
	sync   *entity.SyncConfig
}

// NewClickHouseTarget 创建 ClickHouse 目标
func NewClickHouseTarget(tc *entity.TargetConfig, sync *entity.SyncConfig) (service.SyncTarget, error) {
	if tc.ClickHouse == nil {
		return nil, fmt.Errorf("clickhouse config is required for target %s", tc.Name)
	}
	return &sClickHouseTarget{
		config: tc,
		sync:   sync,
	}, nil
}

// Connect 连接 ClickHouse
func (t *sClickHouseTarget) Connect(ctx context.Context) error {
	ch := t.config.ClickHouse
	conn, err := clickhouse.Open(&clickhouse.Options{
		Addr: []string{fmt.Sprintf("%s:%d", ch.Host, ch.Port)},
		Auth: clickhouse.Auth{
			Database: ch.Database,
			Username: ch.User,
			Password: ch.Password,
		},
		Settings: clickhouse.Settings{
			"max_execution_time": 60,
		},
		DialTimeout: time.Second * 30,
		Compression: &clickhouse.Compression{
			Method: clickhouse.CompressionLZ4,
		},
	})
	if err != nil {
		return fmt.Errorf("connect to clickhouse failed: %v", err)
	}

	if err := conn.Ping(ctx); err != nil {
		return fmt.Errorf("ping clickhouse failed: %v", err)
	}

	t.chConn = conn
	g.Log().Infof(ctx, "Connected to ClickHouse: %s:%d/%s", ch.Host, ch.Port, ch.Database)
	return nil
}

// Close 关闭连接
func (t *sClickHouseTarget) Close() error {
	if t.chConn != nil {
		return t.chConn.Close()
	}
	return nil
}

// OnRow 处理行变更事件
func (t *sClickHouseTarget) OnRow(e *canal.RowsEvent) error {
	if !slices.Contains(t.config.Tables, e.Table.Name) {
		return nil
	}

	switch e.Action {
	case canal.InsertAction:
		return t.handleInsert(e)
	case canal.UpdateAction:
		return t.handleUpdate(e)
	case canal.DeleteAction:
		return t.handleDelete(e)
	}
	return nil
}

// handleInsert 处理 INSERT 事件
func (t *sClickHouseTarget) handleInsert(e *canal.RowsEvent) error {
	ctx := context.Background()
	sql := fmt.Sprintf("INSERT INTO %s.%s", t.config.ClickHouse.Database, e.Table.Name)

	batch, err := t.chConn.PrepareBatch(ctx, sql)
	if err != nil {
		g.Log().Errorf(ctx, "Prepare batch failed: %v", err)
		return err
	}

	for _, row := range e.Rows {
		values := convertRow(row)
		if err := batch.Append(values...); err != nil {
			g.Log().Errorf(ctx, "Append row failed: %v", err)
			continue
		}
	}

	if err := batch.Send(); err != nil {
		g.Log().Errorf(ctx, "Send batch failed: %v", err)
		return err
	}

	g.Log().Infof(ctx, "[%s] Inserted %d rows to %s.%s",
		t.config.Name, len(e.Rows), t.config.ClickHouse.Database, e.Table.Name)
	return nil
}

// handleUpdate 处理 UPDATE 事件
func (t *sClickHouseTarget) handleUpdate(e *canal.RowsEvent) error {
	ctx := context.Background()

	sql := fmt.Sprintf("INSERT INTO %s.%s", t.config.ClickHouse.Database, e.Table.Name)
	batch, err := t.chConn.PrepareBatch(ctx, sql)
	if err != nil {
		g.Log().Errorf(ctx, "Prepare batch failed: %v", err)
		return err
	}

	for i := 0; i < len(e.Rows); i += 2 {
		if i+1 >= len(e.Rows) {
			break
		}
		newRow := e.Rows[i+1]
		values := convertRow(newRow)
		if err := batch.Append(values...); err != nil {
			g.Log().Errorf(ctx, "Append row failed: %v", err)
			continue
		}
	}

	if err := batch.Send(); err != nil {
		g.Log().Errorf(ctx, "Send batch failed: %v", err)
		return err
	}

	g.Log().Infof(ctx, "[%s] Updated %d rows in %s.%s",
		t.config.Name, len(e.Rows)/2, t.config.ClickHouse.Database, e.Table.Name)
	return nil
}

// handleDelete 处理 DELETE 事件
func (t *sClickHouseTarget) handleDelete(e *canal.RowsEvent) error {
	ctx := context.Background()
	pkCols := getPrimaryKeyColumns(e.Table)

	for _, row := range e.Rows {
		var conditions []string
		var values []any
		for _, col := range pkCols {
			for i, tableCol := range e.Table.Columns {
				if tableCol.Name == col && i < len(row) {
					conditions = append(conditions, fmt.Sprintf("%s = ?", col))
					values = append(values, row[i])
					break
				}
			}
		}
		if len(conditions) == 0 {
			g.Log().Errorf(ctx, "No primary key found for table %s", e.Table.Name)
			continue
		}

		sql := fmt.Sprintf("ALTER TABLE %s.%s DELETE WHERE %s",
			t.config.ClickHouse.Database,
			e.Table.Name,
			conditions[0],
		)
		for i := 1; i < len(conditions); i++ {
			sql += " AND " + conditions[i]
		}

		if err := t.chConn.Exec(ctx, sql, values...); err != nil {
			g.Log().Errorf(ctx, "Delete failed: %v", err)
			continue
		}
	}

	g.Log().Infof(ctx, "[%s] Deleted %d rows from %s.%s",
		t.config.Name, len(e.Rows), t.config.ClickHouse.Database, e.Table.Name)
	return nil
}

// OnDDL 处理 DDL 事件
func (t *sClickHouseTarget) OnDDL(header *replication.EventHeader, nextPos mysql.Position, queryEvent *replication.QueryEvent) error {
	if queryEvent == nil {
		return nil
	}
	ctx := context.Background()
	query := string(queryEvent.Query)
	for _, table := range t.config.Tables {
		if strings.Contains(query, table) {
			g.Log().Infof(ctx, "[%s] DDL: %s", t.config.Name, query)
			break
		}
	}
	return nil
}

// Start 启动定时清理任务
func (t *sClickHouseTarget) Start() {
	if t.config.Schedule == nil || !t.config.Schedule.Enable {
		g.Log().Infof(context.Background(), "[%s] Periodic OPTIMIZE is disabled", t.config.Name)
		return
	}

	intervalMinutes := t.config.Schedule.Interval
	if intervalMinutes <= 0 {
		intervalMinutes = 1440
	}

	interval := time.Duration(intervalMinutes) * time.Minute

	go func() {
		ctx := context.Background()
		for {
			g.Log().Infof(ctx, "[%s] Next OPTIMIZE scheduled in %v", t.config.Name, interval)

			timer := time.NewTimer(interval)
			<-timer.C

			t.optimizeTable()
		}
	}()
}

// optimizeTable 执行表优化
func (t *sClickHouseTarget) optimizeTable() {
	ctx := context.Background()

	for _, table := range t.config.Tables {
		startTime := time.Now()

		g.Log().Infof(ctx, "[%s] Starting OPTIMIZE for table %s.%s",
			t.config.Name, t.config.ClickHouse.Database, table)

		sql := fmt.Sprintf("OPTIMIZE TABLE %s.%s FINAL", t.config.ClickHouse.Database, table)
		if err := t.chConn.Exec(ctx, sql); err != nil {
			g.Log().Warningf(ctx, "[%s] Optimize table %s failed: %v", t.config.Name, table, err)
			continue
		}

		elapsed := time.Since(startTime)
		g.Log().Infof(ctx, "[%s] OPTIMIZE completed for %s.%s in %v",
			t.config.Name, t.config.ClickHouse.Database, table, elapsed)
	}
}

// String 返回目标名称
func (t *sClickHouseTarget) String() string {
	return fmt.Sprintf("ClickHouse:%s", t.config.Name)
}

// getPrimaryKeyColumns returns the primary key column names from the table schema.
func getPrimaryKeyColumns(table *schema.Table) []string {
	if table == nil {
		return []string{"id"}
	}

	if len(table.PKColumns) > 0 {
		var pkCols []string
		for _, idx := range table.PKColumns {
			if idx >= 0 && idx < len(table.Columns) {
				pkCols = append(pkCols, table.Columns[idx].Name)
			}
		}
		return pkCols
	}

	// Fallback to first column
	if len(table.Columns) > 0 {
		return []string{table.Columns[0].Name}
	}
	return []string{"id"}
}

// findPrimaryKeyIndex is kept for backward compatibility but no longer used in new code.
// Use getPrimaryKeyColumns instead for multi-column PK support.
func findPrimaryKeyIndex(table *schema.Table) int {
	cols := getPrimaryKeyColumns(table)
	if len(cols) > 0 {
		for i, col := range table.Columns {
			if col.Name == cols[0] {
				return i
			}
		}
	}
	return 0
}

// convertRow 转换行数据（追加 _version 时间戳）
func convertRow(row []any) []any {
	values := make([]any, len(row))
	copy(values, row)
	values = append(values, time.Now().UnixNano())
	return values
}
